### ISSUE TITLE
Ask/Tell Interface Custom Number of Solutions Bug 

### ISSUE THREAD

**Issue by LennartPurucker** [CMA-ES/pycma#224] opened 2023-01-27 12:05 UTC
Hey,

I think there might be a bug within the ask/tell interface of `CMAEvolutionStrategy` regarding the option of `ask()` to return a custom number of solutions (`number`).

## Explanation
When one uses `ask(number=X)` with `mu < X << popsize`,  the median can potentially not be calculated due to an index error.

_(TBH, I am not even sure if one should even set X such that `mu < X << popsize`, but I am using it right now to process a smaller batch of solutions.)_

## Minimal Code Example
With CMA Version 3.3.0; Python 3.9

```python
import cma


opts = cma.CMAOptions()
opts.set("seed", 1)
opts.set("popsize", 25)

fun = cma.ff.elli
x0 = 4 * [2]
sigma0 = 1

es = cma.CMAEvolutionStrategy(x0, sigma0, inopts=opts)

for _ in range(10):
    solutions = es.ask()
    es.tell(solutions, [fun(s) for s in solutions])


solutions = es.ask(number=12)
es.tell(solutions, [fun(s) for s in solutions])
```

Crashes with:
```
    fit.median = (fit.fit[self.popsize // 2] if self.popsize % 2
IndexError: index 12 is out of bounds for axis 0 with size 12
```

## Potentail Solution 
We might need to switch `self.popsize` with `lam` in the [computation of the median](https://github.com/CMA-ES/pycma/blob/development/cma/evolution_strategy.py#L2767).  

Old:
```python
        fit.median = (fit.fit[self.popsize // 2] if self.popsize % 2
                      else np.mean(fit.fit[self.popsize // 2 - 1: self.popsize // 2 + 1]))
```

New:
```python
        fit.median = (fit.fit[lam // 2] if lam  % 2
                      else np.mean(fit.fit[lam  // 2 - 1: lam  // 2 + 1]))
```

This worked for me.

**Comment by nikohansen** [comment] 2023-01-27 15:53
Thanks for the catch!

Calling tell with a small number of solutions is indeed not a use case the code was designed for. More importantly, the algorithm is expected to work poorly or fail in this case, because the internal parameter settings crucially depend on the population size.

The code should probably output a warning and proceed.

**Comment by LennartPurucker** [comment] 2023-01-27 15:58
Ah okay, thanks for the clarification!

Feel free to close this issue - I am not sure if you want to keep it open or not.

**Comment by nikohansen** [comment] 2023-01-28 15:47
Will be fixed in upcoming code.

**Closed by nikohansen** 2023-01-28 15:47 UTC
Labels: semi-bug
