### ISSUE TITLE
Test fail on windows

### ISSUE THREAD

**Issue by rissom** [CMA-ES/pycma#53] opened 2018-02-15 10:45 UTC
I use the Anaconda python distribution and installed cma through pip. When I run the test.py file I get the following error messages:

`C:\Users\thorsten.rissom\cma-test>python` "c:/Program Files/Anaconda3/Lib/site-packages/cma/test.py"
doctesting `cma` package (v2.3.1) by calling `doctest_files`:
doctesting constraints_handler.py ...     TestResults(failed=0, attempted=19)
doctesting evolution_strategy.py ...      TestResults(failed=0, attempted=103)
doctesting fitness_functions.py ...       TestResults(failed=0, attempted=0)
doctesting fitness_transformations.py ... TestResults(failed=0, attempted=80)
doctesting interfaces.py ...              TestResults(failed=0, attempted=3)
doctesting optimization_tools.py ...      TestResults(failed=0, attempted=14)
doctesting purecma.py ...                 **********************************************************************
File "c:/Program Files/Anaconda3/Lib/site-packages/cma\purecma.py", line 491, in purecma.py
Failed example:
    logger = pcma.CMAESDataLogger().load()
Exception raised:
    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\doctest.py", line 1321, in __run
        compileflags, 1), test.globs)
      File "<doctest purecma.py[1]>", line 1, in <module>
        logger = pcma.CMAESDataLogger().load()
      File "C:\Program Files\Anaconda3\lib\site-packages\cma\purecma.py", line 677, in load
        with open(name or self.filename, 'r') as f:
    FileNotFoundError: [Errno 2] No such file or directory: '_CMAESDataLogger_datadict.py'
**********************************************************************
File "c:/Program Files/Anaconda3/Lib/site-packages/cma\purecma.py", line 492, in purecma.py
Failed example:
    logger.filename == "_CMAESDataLogger_datadict.py"
Exception raised:
    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\doctest.py", line 1321, in __run
        compileflags, 1), test.globs)
      File "<doctest purecma.py[2]>", line 1, in <module>
        logger.filename == "_CMAESDataLogger_datadict.py"
    NameError: name 'logger' is not defined
**********************************************************************
1 items had failures:
   2 of  31 in purecma.py
***Test Failed*** 2 failures.
TestResults(failed=2, attempted=31)
doctesting recombination_weights.py ...   TestResults(failed=0, attempted=25)
doctesting sampler.py ...                 TestResults(failed=0, attempted=28)
doctesting sigma_adaptation.py ...        TestResults(failed=0, attempted=11)
doctesting test.py ...                    TestResults(failed=0, attempted=72)
doctesting transformations.py ...         **********************************************************************
File "c:/Program Files/Anaconda3/Lib/site-packages/cma\transformations.py", line 66, in transformations.py
Failed example:
    print(R(R(x), inverse=1))
Expected:
    [ 1.  2.  3.]
Got:
    [1. 2. 3.]
**********************************************************************
File "c:/Program Files/Anaconda3/Lib/site-packages/cma\transformations.py", line 223, in transformations.py
Failed example:
    tf([1.52, -2.2, -0.2, 2, 4, 10.4])
Expected:
    array([  1.52,   4.  ,   2.  ,   2.  ,   4.  ,  10.4 ])
Got:
    array([ 1.52,  4.  ,  2.  ,  2.  ,  4.  , 10.4 ])
**********************************************************************
1 items had failures:
   2 of  28 in transformations.py
***Test Failed*** 2 failures.
TestResults(failed=2, attempted=28)
doctesting utilities\math.py ...          TestResults(failed=0, attempted=0)
doctesting utilities\utils.py ...         TestResults(failed=0, attempted=57)
`

I checked if the file "_CMAESDataLogger_datadict.py" is there, and it is in the cma directory. I suspect that there is a problem with the path notation of windows, but I could be wrong.

**Comment by nikohansen** [comment] 2018-02-15 17:57
Thanks for the feedback! I think the problem is in the test setup, and it might already be solved in the current `master` branch. If you run the test a second time it may succeed, because now the file already exists. Did you try this?

If you see the same problem on a clean check out using
```
pip install git+https://github.com/CMA-ES/pycma.git@master
```
please let me know!

**Comment by nikohansen** [comment] 2018-02-18 01:49
The second failure was related to changes in `numpy`. This should be fixed with the latest [release `v2.5.3` also on PyPI](https://pypi.python.org/pypi/cma/2.5.3).

**Closed by nikohansen** 2018-02-18 01:49 UTC
